name: Build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Install dependencies
      run: yarn
    - name: Build Linux
      run: yarn build:linux

  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Install dependencies
      run: yarn
    - name: Build Mac
      run: yarn build:mac

  build_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: Install dependencies
      run: yarn
    - name: Build Windows
      run: yarn build:win
